name: Workflow with Local Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run local custom action
        uses: ./custom-actions/test-action
        with:
          input-param: "test-value"
          
      - name: Another local action
        uses: ./scripts/deploy-action.yml
        with:
          environment: production
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Local deployment action
        uses: ./scripts/deploy-action.yml
        with:
          deployment-target: production
